### ISSUE TITLE
日報送信ボタンの配置について

### ISSUE THREAD

**Issue by shoji-watanabe** [nisshiee/nippo#20]
### タグ
- 【WANT】【コンセプトによる】

### 問題点
- モニタサイズによって、日報送信ボタンが一画面に表示されないケースがある

### 解決策（案）
- 見た目がダサくなることを覚悟で、日報送信ボタンを上部に表示させる

↓こんな感じで「日報送信」ボタンが表示されない。
（電話番号写ってたのでSS消しました by:西岡）

**Comment by shoji-watanabe** [comment]
にゃははw
サンクス :)

**Comment by nisshiee** [comment]
試しにボタンを上に配置してみました
感想くださいｗ

**Comment by shoji-watanabe** [comment]
お、いいじゃない！
ブラウザ全画面だと右ににょーんていっちゃうけど、気にならない！

にょーん
![image](https://cloud.githubusercontent.com/assets/12958968/15862903/253be750-2d0c-11e6-9fb0-983ad84ced4c.png)

こっちのほうが助かる！

**Comment by nisshiee** [comment]
@shoji-watanabe ではこのissueは一旦クローズします
ボタン右過ぎて使いにくいとかあればまたissueあげてくださいー

ちなみに以下は玄人向けですが、
本文テキストエリア→送信ボタン
の順にtabindexを貼っているので、Tabキーでフォーカス移動していくのが楽ですｗ
