### ISSUE TITLE
テンプレート画面の見栄えについて

### ISSUE THREAD

**Issue by takuya-matsuo** [nisshiee/nippo#21]
テンプレート画面と日報送信画面が、ぱっとみで判別できないので、少し違いを出して欲しい

日報送信画面で書いたつもりが、テンプレート画面だったということがあった

**Comment by nisshiee** [comment]
たしかに・・・
とは思うものの、どう変えるかイメージ湧いてないので意見募集

**Comment by shoji-watanabe** [comment]
- 入力スペースの文字色を変える
- 「テンプレート」とアイコンをつける

**Comment by takuya-matsuo** [comment]
グローバルナビに色を付ける、とか

**Comment by takuya-matsuo** [comment]
あ、でも昌司さんがイシューに挙げている、
送信ボタンが上にくることで解決される問題かもしれないですね！

ボタンがあればどっちかわかるので。

**Comment by nisshiee** [comment]
> 今いる画面の方のグローバルナビに色を付ける

これはそもそも「判別できない」の文脈とは別にやりたいな

> 「テンプレート」とアイコンをつける

これをよさ気にやるのと、他の施策との組み合わせっていう感じをとりあえず試してみます

**Comment by nisshiee** [comment]
#20 のボタンを上にもってくるやつと、
グローバルナビの色付けだけやりましたが、
いかがでしょう？

**Comment by shoji-watanabe** [comment]
はやっ！

いや、ただ、意外とこれ、まだ間違えるかも。。。
ただ、俺は注意力足りないので何とも言えないから他の人の意見も聞きたいな。。

**Comment by nisshiee** [comment]
> 「テンプレート」とアイコンをつける
これもやってみますかね

**Comment by nisshiee** [comment]
#31 で南さんが背景色を別々にしてくれましたが、どうでしょ

**Comment by shoji-watanabe** [comment]
いけてる。

あと、ここまでやったらもう存分に差がついたので、これ以上やる必要は無いと思うけど、

あえていうなら、そもそも、「テンプレ編集」と「日報作成」のリンクが、
同じグローバルナビに同じ文字の大きさと色で並んでいることがわかりにくくさせているな、とも思った。

**Comment by nisshiee** [comment]
いつかテンプレ編集リンクを右の方に動かそうとは思ってるんですが、
最初1回テンプレ編集しないと件名「部署 名前」で送信されちゃう問題も抱えてるので、
今すぐ動かすのちょっと躊躇ってるんですよね・・・

どうせ機能増えてグローバルナビの項目も増えてくると思うんで、そのタイミングでの見直しにしたいっす
