### ISSUE TITLE
「部署 名前」だったら送信出来ないようにするか警告出す

### ISSUE THREAD

**Issue by iida-hayato** [nisshiee/nippo#33]

**Comment by nisshiee** [comment]
若干不本意だけどやります 😢

**Comment by nisshiee** [comment]
![2016-06-09 20 31 35](https://cloud.githubusercontent.com/assets/480925/15928371/7025aa5a-2e81-11e6-8012-3b6f2f72a050.png)
ここまでやった

**Comment by nisshiee** [comment]
released

**Comment by iida-hayato** [comment]
closeして良いんだろうかこれ?w

**Comment by nisshiee** [comment]
別の方法考えますｗ
警告を増やしてもダメな予感
