### ISSUE TITLE
faviconがほしい

### ISSUE THREAD

**Issue by hatappi** [nisshiee/nippo#36]
バーに並べた時に素早く見つけたい
<img width="97" alt="2016-06-10 9 22 23" src="https://cloud.githubusercontent.com/assets/3453977/15950787/f4e9bbda-2eec-11e6-82c7-94cf776a166f.png">

**Comment by nisshiee** [comment]
ですよねー
@ystkmnm ﾁﾗｯﾁﾗｯ

**Comment by ystkmnm** [comment]
やります

**Comment by nisshiee** [comment]
断りづらい振りしてすませんｗ
厳しかったらパスしていいすよｗ

**Comment by ystkmnm** [comment]
@nisshiee どんどん振ってください！できるときにやります。

**Comment by ystkmnm** [comment]
https://github.com/nisshiee/nippo/pull/38
こちらにて対応しました。

**Comment by nisshiee** [comment]
released!
