### ISSUE TITLE
時間経ってもYou need to sign in or sign up before continuingにならないようにしてほしい

### ISSUE THREAD

**Issue by takakazumatsuyama** [nisshiee/nippo#41]
![slack for ios upload](https://cloud.githubusercontent.com/assets/1006297/15960919/127711a2-2f3d-11e6-80e6-4f09eeee7c21.png)

**Comment by nisshiee** [comment]
@takakazumatsuyama @shoji-watanabe 
軽く調査して見つかった原因は潰したんで、しばらく使ってみて直ったか教えてくださいー

**Comment by nisshiee** [comment]
来週月曜あたりで問題報告なければ閉じます

**Comment by takakazumatsuyama** [comment]
オッケー！

**Comment by takakazumatsuyama** [comment]
再現したわー

**Comment by nisshiee** [comment]
(´；ω；｀)

**Comment by hiragram** [comment]
@takakazumatsuyama これプライベートブラウズだからでは？

**Comment by nisshiee** [comment]
えっ？ｗ

**Comment by takakazumatsuyama** [comment]
ほんまやｗ

**Comment by nisshiee** [comment]
ｗｗｗｗｗ

**Comment by hiragram** [comment]
関係ない？

**Comment by takakazumatsuyama** [comment]
システム関係ねえわｗ

**Comment by hiragram** [comment]
ワロタ

**Comment by takakazumatsuyama** [comment]
普段safari使わんから、プライベートモードにしてること忘れてたｗ

**Comment by nisshiee** [comment]
普通にCookie認証してるんで、プライベートモードじゃないやつでセッション切れる場合は教えてくだせぇ

**Comment by nisshiee** [comment]
@shoji-watanabe というわけで、来週ぐらいまでに昌司さんも問題無さそうなら完了にしますー

**Comment by shoji-watanabe** [comment]
@nisshiee 
問題なかった！！！

**Comment by shoji-watanabe** [comment]
done！！

**Comment by nisshiee** [comment]
ざす！
