### ISSUE TITLE
ログイン許可ユーザの厳密なValidation

### ISSUE THREAD

**Issue by nisshiee** [nisshiee/nippo#49]
今 `@speee.jp` ユーザを許可してるけど、厳密には派遣さん等はだめで、うまく権限コントロールが必要

**Comment by nisshiee** [comment]
1回は日報を送らないと閲覧権限が付与されない
とかは簡単にできそう

**Comment by nisshiee** [comment]
でも、新規ユーザ獲得の導線としてはそれを潰しちゃうのは惜しいな・・・

**Comment by nisshiee** [comment]
暫定対応案

- ホワイトリスト
  - 自分でallメンバー把握はできるのでホワイトリスト作れる
  - 定常運用が発生
- GMailAPIで「日報を受信してるか」をチェック
  - 実装ダルい
  - 脱メールしたら使えない

恒久対応案

- 管理部から情報もらえる口があると嬉しいなぁ
- 何回か日報を「送る」ことによって実績が解除されて閲覧権限がもらえる

**Comment by Kohtaro-NISHI** [comment]
派遣さんの中に `@speee.jp` ユーザっていらっしゃるんですか？

**Comment by nisshiee** [comment]
ホワイトリスト認証 + ホワイトリスト生成バッチで行く

**Comment by nisshiee** [comment]
Done!!!!!!!!!
