### ISSUE TITLE
作成途中の日報を保存したい

### ISSUE THREAD

**Issue by KoishiYMM** [nisshiee/nippo#55]
PCで日報を作成してて途中で帰らないといけなくなることとか多いので、そのあと続きをスマホで作成できたらとてもうれしい。

**Comment by nisshiee** [comment]
ちょっと小手先のごまかしじゃなくてちゃんと設計したほうが良さそうなので、ちょっと時間ください

**Comment by KoishiYMM** [comment]
めんどくさい要求になってしまってごめんなさい！
ありがとうございます。

**Comment by nisshiee** [comment]
リリースしましたー！！ 🎉 
使い勝手については改善の余地もあるかと思いますので、
また要望おなしゃす！
