### ISSUE TITLE
送信時に作成画面で何秒かステイした後、こういうエラーが発生する

### ISSUE THREAD

**Issue by takakazumatsuyama** [nisshiee/nippo#59]
![slack for ios upload 1](https://cloud.githubusercontent.com/assets/1006297/16251057/dc0e2432-385d-11e6-8e9c-703fd7678356.png)

**Comment by nisshiee** [comment]
@takakazumatsuyama これ、いつ起きたかわかります・・・？
できるだけ正確に・・・

**Comment by hiragram** [comment]
これ、裏では送信失敗した時になるやつな気がする
僕も見たことある

**Comment by nisshiee** [comment]
この画面自体は
https://github.com/nisshiee/nippo/blob/master/public/500.html
これそのまま表示してるだけだから、
「何かが起こった」ということはわかるけど、
「何が起きたか」はわからないんすよ
（違うことが起きてるかもしれない）

**Comment by nisshiee** [comment]
続報ないんで閉じます
